### PR TITLE
v0.83.8

### PR DESCRIPTION
**Pull request by nicola-sorace**

### CODE REVIEW

**Comment by mtinning** [comment]
@nicola-sorace I think you might need to do `git push origin --tags` on the this repo to get it to publish

**Comment by nicola-sorace** [comment]
@mtinning Thanks, I think that worked

**Comment by mtinning** [comment]
Build failed after publish, I think this is fine:

**Comment by nicola-sorace** [comment]
The published version seems to work fine. Don't know what the failure is about.

**Pull request merged**
